# Generated by Django 4.2.3 on 2024-07-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='registration',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='registration',
            name='category',
            field=models.CharField(choices=[('GM', 'General Medicine'), ('OR', 'Orthopedics'), ('SU', 'Surgery'), ('PE', 'Pediatrics'), ('GY', 'Gynecology'), ('NE', 'Neurology'), ('ON', 'Oncology')], default='GM', max_length=2),
        ),
        migrations.AddField(
            model_name='registration',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
